# Generated by Django 6.0.3 on 2026-04-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="clerk_verified",
        ),
        migrations.RemoveField(
            model_name="student",
            name="clerk_verified_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="fees_verified",
        ),
        migrations.RemoveField(
            model_name="student",
            name="fees_verified_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="principle_verified",
        ),
        migrations.RemoveField(
            model_name="student",
            name="principle_verified_at",
        ),
    ]
