# Generated by Django 6.0.3 on 2026-04-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_id", models.IntegerField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="student_documents/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_documents",
                        to="sms_app.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="sms_app.student",
                    ),
                ),
            ],
        ),
    ]
