# Generated by Django 6.0.3 on 2026-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
