# Generated by Django 6.0.3 on 2026-04-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
