# Generated by Django 6.0.3 on 2026-04-11 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="school_class",
            field=models.CharField(
                choices=[
                    ("nursery", "Nursery"),
                    ("lkg", "LKG"),
                    ("ukg", "UKG"),
                    ("class1", "Class 1"),
                    ("class2", "Class 2"),
                    ("class3", "Class 3"),
                    ("class4", "Class 4"),
                    ("class5", "Class 5"),
                    ("class6", "Class 6"),
                    ("class7", "Class 7"),
                    ("class8", "Class 8"),
                    ("class9", "Class 9"),
                    ("class10", "Class 10"),
                    ("class11_science", "Class 11 Science"),
                    ("class11_arts", "Class 11 Arts"),
                    ("class11_commerce", "Class 11 Commerce"),
                    ("class12_science", "Class 12 Science"),
                    ("class12_arts", "Class 12 Arts"),
                    ("class12_commerce", "Class 12 Commerce"),
                ],
                max_length=70,
            ),
        ),
        migrations.AlterField(
            model_name="tt_day",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.schoolclass",
            ),
        ),
    ]
