# Generated by Django 6.0.3 on 2026-04-06 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_alter_school_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionform",
            name="fee_type",
            field=models.CharField(
                blank=True,
                choices=[("general", "General"), ("individual", "Individual")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AdmissionFeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fee_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "admission_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="sms_app.admissionform",
                    ),
                ),
            ],
        ),
    ]
