# Generated by Django 6.0.3 on 2026-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_alter_schoolclass_school_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="school_class",
            field=models.CharField(
                choices=[
                    ("nursery", "Nursery"),
                    ("lkg", "LKG"),
                    ("ukg", "UKG"),
                    ("class1", "Class 1"),
                    ("class2", "Class 2"),
                    ("class3", "Class 3"),
                    ("class4", "Class 4"),
                    ("class5", "Class 5"),
                    ("class6", "Class 6"),
                    ("class7", "Class 7"),
                    ("class8", "Class 8"),
                    ("class9_basic", "Class 9 Basic Math"),
                    ("class9_standard", "Class 9 Standard Math"),
                    ("class9_advanced", "Class 9 Advanced Math"),
                    ("class10_basic", "Class 10 Basic Math"),
                    ("class10_standard", "Class 10 Standard Math"),
                    ("class10_advanced", "Class 10 Advanced Math"),
                    ("class11_science", "Class 11 Science"),
                    ("class11_arts", "Class 11 Arts"),
                    ("class11_commerce", "Class 11 Commerce"),
                    ("class12_science", "Class 12 Science"),
                    ("class12_arts", "Class 12 Arts"),
                    ("class12_commerce", "Class 12 Commerce"),
                ],
                max_length=70,
            ),
        ),
    ]
