# Generated by Django 6.0.3 on 2026-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_admissiondocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="map_to_student_field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
