# Generated by Django 6.0.3 on 2026-04-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_delete_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="phone_number",
            new_name="mobile",
        ),
    ]
