# Generated by Django 6.0.3 on 2026-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_remove_student_clerk_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="clerk_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="clerk_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="fees_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="fees_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="principle_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="principle_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
