# Generated by Django 6.0.3 on 2026-04-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_studentdocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdocument",
            name="document",
        ),
        migrations.RemoveField(
            model_name="studentdocument",
            name="student",
        ),
    ]
