# Generated by Django 6.0.3 on 2026-04-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0003_formfield_map_to_student_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="admission_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
