# Generated by Django 6.0.3 on 2026-04-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0003_remove_studentdocument_document_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentDocument",
            new_name="DocumentField",
        ),
    ]
