# Generated by Django 6.0.3 on 2026-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0003_student_clerk_verified_student_clerk_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gr_no",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
