# Generated by Django 6.0.3 on 2026-04-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0003_admissionform_fee_type_admissionfeestructure"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nursery", "Nursery"),
                            ("lkg", "LKG"),
                            ("ukg", "UKG"),
                            ("class_1", "Class 1"),
                            ("class_2", "Class 2"),
                            ("class_3", "Class 3"),
                            ("class_4", "Class 4"),
                            ("class_5", "Class 5"),
                            ("class_6", "Class 6"),
                            ("class_7", "Class 7"),
                            ("class_8", "Class 8"),
                            ("class_9", "Class 9"),
                            ("class_10", "Class 10"),
                            ("class_11", "Class 11"),
                            ("class_12", "Class 12"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("science", "Science"),
                            ("commerce", "Commerce"),
                            ("arts", "Arts"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="admissionform",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="sms_app.schoolclass",
            ),
        ),
    ]
