# Generated by Django 6.0.3 on 2026-04-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0004_schoolclass_admissionform_school_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="school_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nursery", "Nursery"),
                    ("lkg", "LKG"),
                    ("ukg", "UKG"),
                    ("class_1", "Class 1"),
                    ("class_2", "Class 2"),
                    ("class_3", "Class 3"),
                    ("class_4", "Class 4"),
                    ("class_5", "Class 5"),
                    ("class_6", "Class 6"),
                    ("class_7", "Class 7"),
                    ("class_8", "Class 8"),
                    ("class_9", "Class 9"),
                    ("class_10", "Class 10"),
                    ("class_11", "Class 11"),
                    ("class_12", "Class 12"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="stream",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
