# Generated by Django 6.0.3 on 2026-04-13 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0004_tt_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionfee",
            name="status",
        ),
        migrations.AddField(
            model_name="admissionfee",
            name="fee_verify",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admissionfee",
            name="payment_mode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="admissionfee",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.student",
            ),
        ),
    ]
