# Generated by Django 6.0.3 on 2026-04-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0004_admission_admission_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionfee",
            name="student",
        ),
        migrations.AddField(
            model_name="admissionfee",
            name="admission_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
