# Generated by Django 6.0.3 on 2026-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0004_student_gr_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gr_no",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
