# Generated by Django 6.0.3 on 2026-04-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0004_module_usermoduleaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="category",
            field=models.CharField(default="OTHER", max_length=20),
        ),
    ]
