# Generated by Django 6.0.3 on 2026-04-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0004_announcement_school_announcementtarget_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionform",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="announcementtarget",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("ROLE", "Role"),
                    ("CLASS", "Class"),
                    ("SPECIFIC", "Specific User"),
                ],
                max_length=10,
            ),
        ),
    ]
