# Generated by Django 6.0.3 on 2026-04-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_remove_admissionfee_status_admissionfee_fee_verify_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionfee",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee",
                to="sms_app.student",
            ),
        ),
    ]
