# Generated by Django 6.0.3 on 2026-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_alter_admissionform_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEACHER", "Teacher"),
                    ("CLERK", "Clerk"),
                    ("LIBRARIAN", "Librarian"),
                    ("FEE MANAGEMENT", "Fee Management "),
                    ("PRINCIPAL", "Principal"),
                    ("TRANSOPORTATION", "Transportation "),
                    ("INVENTORY", "Inventory "),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
