# Generated by Django 6.0.3 on 2026-04-24 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_remove_admissionfee_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="fee_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="fee_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admission",
            name="fee_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="fee_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_fees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
