# Generated by Django 6.0.3 on 2026-04-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_alter_staff_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
