# Generated by Django 6.0.3 on 2026-04-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_alter_schoolclass_school_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="stream",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
