# Generated by Django 6.0.3 on 2026-04-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0006_alter_documentfield_form_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfield",
            name="form_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label",
                to="sms_app.admissionform",
            ),
        ),
    ]
