# Generated by Django 6.0.3 on 2026-04-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0006_alter_schoolclass_stream"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionform",
            name="school_class",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="stream",
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="sms_app.schoolclass",
                    ),
                ),
            ],
        ),
    ]
