# Generated by Django 6.0.3 on 2026-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0006_studentdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="form_filled",
            field=models.BooleanField(default=False),
        ),
    ]
