# Generated by Django 6.0.3 on 2026-04-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0007_alter_documentfield_form_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentfieldvalue",
            name="file",
        ),
        migrations.AddField(
            model_name="student",
            name="mobile",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
