# Generated by Django 6.0.3 on 2026-04-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0007_remove_admissionform_school_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="school_class",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name="Stream",
        ),
    ]
