# Generated by Django 6.0.3 on 2026-04-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0007_student_form_filled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="course",
        ),
        migrations.RemoveField(
            model_name="student",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="student",
            name="roll_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="year",
        ),
    ]
