# Generated by Django 6.0.3 on 2026-04-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0008_perents_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tt_day",
            name="school_class",
        ),
        migrations.AddField(
            model_name="tt_day",
            name="class_div",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.division",
            ),
        ),
    ]
