# Generated by Django 6.0.3 on 2026-04-09 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0008_remove_studentfieldvalue_file_student_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfieldvalue",
            name="form_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.admissionform",
            ),
        ),
    ]
