# Generated by Django 6.0.3 on 2026-04-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0008_remove_student_address_remove_student_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdocument",
            name="student",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="StudentDocument",
        ),
    ]
