# Generated by Django 6.0.3 on 2026-04-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0008_alter_schoolclass_school_class_delete_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.schoolclass",
            ),
        ),
    ]
