# Generated by Django 6.0.3 on 2026-04-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0009_student_school"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="school",
            new_name="school_class",
        ),
    ]
