# Generated by Django 6.0.3 on 2026-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0009_remove_tt_day_school_class_tt_day_class_div"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tt_day",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
