# Generated by Django 6.0.3 on 2026-04-03 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0009_remove_studentdocument_student_delete_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "unique_link",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_forms",
                        to="sms_app.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="sms_app.admissionform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("file", "File"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, null=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="sms_app.formsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("form_filled", models.BooleanField(default=False)),
                ("principle_verified", models.BooleanField(default=False)),
                ("fees_verified", models.BooleanField(default=False)),
                ("clerk_verified", models.BooleanField(default=False)),
                ("principle_verified_at", models.DateTimeField(blank=True, null=True)),
                ("clerk_verified_at", models.DateTimeField(blank=True, null=True)),
                ("fees_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gr_no",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.admissionform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("label", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="student_files/"),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="sms_app.formfield",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_values",
                        to="sms_app.student",
                    ),
                ),
            ],
        ),
    ]
