# Generated by Django 6.0.3 on 2026-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0009_studentfieldvalue_form_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("radio", "Radio"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
