# Generated by Django 6.0.3 on 2026-04-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0010_rename_school_student_school_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionfeestructure",
            name="class_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.schoolclass",
            ),
        ),
    ]
