# Generated by Django 6.0.3 on 2026-04-14 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0010_alter_tt_day_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Time_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.TimeField(blank=True, null=True)),
                ("end", models.TimeField(blank=True, null=True)),
                ("day", models.CharField(blank=True, max_length=50, null=True)),
                ("slot", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "class_div",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.division",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.staff",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.tt_year",
                    ),
                ),
            ],
        ),
    ]
