# Generated by Django 6.0.3 on 2026-04-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0010_admissionform_formsection_formfield_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="sms_app.admissionform",
            ),
        ),
    ]
