# Generated by Django 6.0.3 on 2026-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0010_alter_formfield_field_type_alter_student_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="mobile",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
