# Generated by Django 6.0.3 on 2026-04-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0011_alter_student_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="form_filled",
            new_name="details_done",
        ),
    ]
