# Generated by Django 6.0.3 on 2026-04-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0011_alter_admissionfeestructure_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="division",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
