# Generated by Django 6.0.3 on 2026-04-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0011_alter_student_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.admissionform"
            ),
        ),
    ]
