# Generated by Django 6.0.3 on 2026-07-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0012_certificatetemplate_certificatetemplatefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveperday",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
