# Generated by Django 6.0.3 on 2026-07-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0012_certificatetemplate_certificatetemplatefield"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkSubmissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="homework_submissions/")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="sms_app.homework",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="sms_app.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("homework", "student")},
            },
        ),
        migrations.DeleteModel(
            name="HomeworkSubmission",
        ),
    ]
