# Generated by Django 6.0.3 on 2026-07-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0013_homeworksubmissions_delete_homeworksubmission"),
        ("sms_app", "0013_leaveperday_is_paid"),
    ]

    operations = []
