# Generated by Django 6.0.3 on 2026-04-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0013_tt_day_tt_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="dtails_done",
            new_name="details_done",
        ),
    ]
