# Generated by Django 6.0.3 on 2026-04-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0013_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formresponse",
            name="form",
        ),
        migrations.RemoveField(
            model_name="studentdocument",
            name="student",
        ),
        migrations.DeleteModel(
            name="Field",
        ),
        migrations.DeleteModel(
            name="Form",
        ),
        migrations.DeleteModel(
            name="FormResponse",
        ),
        migrations.DeleteModel(
            name="StudentDocument",
        ),
    ]
