# Generated by Django 6.0.3 on 2026-04-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0013_admissiondocument_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("half_yearly", "Half-Yearly"),
                    ("yearly", "Yearly"),
                ],
                max_length=20,
            ),
        ),
    ]
