# Generated by Django 6.0.3 on 2026-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0014_rename_dtails_done_student_details_done"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tt_breaks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tt_day",
            name="lecture",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tt_day",
            name="day",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
