# Generated by Django 6.0.3 on 2026-04-30 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0014_alter_feestructure_billing_cycle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feestructure",
            name="school_class",
        ),
        migrations.AddField(
            model_name="feestructure",
            name="scope",
            field=models.CharField(
                blank=True,
                choices=[("class", "Class Wise"), ("global", "All Students")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feetype",
            name="billing_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("half_yearly", "Half-Yearly"),
                    ("yearly", "Yearly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="payment_mode",
            field=models.CharField(
                choices=[("cash", "Cash"), ("online", "Online")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="billing_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("half_yearly", "Half-Yearly"),
                    ("yearly", "Yearly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="fee_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.feetype",
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),
        migrations.CreateModel(
            name="FeeWiseClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.schoolclass",
                    ),
                ),
            ],
        ),
    ]
