# Generated by Django 6.0.3 on 2026-04-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0014_remove_formresponse_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionform",
            name="fees",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="admissionform",
            name="fees_enable",
            field=models.BooleanField(default=False),
        ),
    ]
