# Generated by Django 6.0.3 on 2026-04-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0014_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.staff",
            ),
        ),
    ]
