# Generated by Django 6.0.3 on 2026-04-30 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sms_app",
            "0015_remove_feestructure_school_class_feestructure_scope_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feepayment",
            name="installment",
        ),
        migrations.RemoveField(
            model_name="feepayment",
            name="student",
        ),
        migrations.AddField(
            model_name="feewiseclass",
            name="feetype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.feetype",
            ),
        ),
        migrations.DeleteModel(
            name="FeeInstallment",
        ),
        migrations.DeleteModel(
            name="FeePayment",
        ),
    ]
