# Generated by Django 6.0.3 on 2026-04-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0015_admissionform_fees_admissionform_fees_enable"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.student",
                    ),
                ),
            ],
        ),
    ]
