# Generated by Django 6.0.3 on 2026-04-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0016_admissionfee"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionfee",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
