# Generated by Django 6.0.3 on 2026-04-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0016_remove_feepayment_installment_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentFee",
        ),
    ]
