# Generated by Django 6.0.3 on 2026-04-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0017_admissionfee_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionfee",
            name="student",
        ),
    ]
