# Generated by Django 6.0.3 on 2026-04-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0017_delete_studentfee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feewiseclass",
            name="feetype",
        ),
        migrations.RemoveField(
            model_name="feewiseclass",
            name="school",
        ),
        migrations.RemoveField(
            model_name="feewiseclass",
            name="school_class",
        ),
        migrations.DeleteModel(
            name="FeeStructure",
        ),
        migrations.DeleteModel(
            name="FeeWiseClass",
        ),
    ]
