# Generated by Django 6.0.3 on 2026-04-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0024_academicyear_month_window"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentVerify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gr_no", models.CharField(max_length=50)),
                ("clerk_verify", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.student",
                    ),
                ),
            ],
        ),
    ]
