# Generated by Django 6.0.3 on 2026-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0025_studentverify"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentverify",
            name="admission_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
