# Generated by Django 6.0.3 on 2026-05-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0026_studentverify_admission_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="for_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.feature",
            ),
        ),
    ]
