# Generated by Django 6.0.3 on 2026-05-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0027_module_for_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="check_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
