# Generated by Django 6.0.3 on 2026-05-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0031_salarycomponent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalaryComponent",
        ),
    ]
